name: deploy

on:
  push:
    branches:
      - main # Set a branch to deploy from

jobs:
  deploy:
    runs-on: ubuntu-20.04 # The OS to run the job on
    steps:
      - uses actions/checkout@v2
      - uses actions/setup-node@v1
      - with:
          node-version: '20.x' # The Node.js version to use
      - run: npm ci
      - run: npm run build
      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # The directory to deploy
          user_name: 'Ronan' # The commit author name
